version: '3.8'

services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - MOVIES_SERVICE_HOST=movies
      - MOVIES_SERVICE_PORT=5001
      - SHOWTIMES_SERVICE_HOST=showtimes
      - SHOWTIMES_SERVICE_PORT=5002
      - USERS_SERVICE_HOST=users
      - USERS_SERVICE_PORT=5000
      - BOOKING_SERVICE_HOST=booking
      - BOOKING_SERVICE_PORT=5003
    depends_on:
      - etcd
      - movies
      - showtimes
      - users
      - booking

  movies:
    build: ./movies
    ports:
      - "5001:5001"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      - etcd

  showtimes:
    build: ./showtimes
    ports:
      - "5002:5002"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      - etcd

  users:
    build: ./users
    ports:
      - "5000:5000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      - etcd

  booking:
    build: ./booking
    ports:
      - "5003:5003"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      - etcd

volumes:
  etcd_data:
    driver: local